'\\\\\\\\\\\\\\\\\\\\\\\\\ DECLARATIONS /////////////////////////

' Currently working on CR-6 2024-11-21

'send.cwop.rest service
Public CWOPString2 As String * 256
Public dateTime As String

'Example Weather Data
Const Temp=32
Const rH=97
Const Rain=1

'Format Time String
Public Response As String * 1000
Public Header As String * 500
Public SocketRef As Long
Public TimeArray(9) As Long
Public GMTTime(7) As Long
Public DaysInMonth(12) As Long = {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31}
Public TimerCount As Long ' Timer to track elapsed seconds

'\\\\\\\\\\\\\\\\\\\\\\\\\\\ PROGRAM ///////////////////////////

BeginProg
  TimerCount = 0
    Scan(1,Sec, 3, 0)
    'Configure GMT Time
    RealTime(TimeArray)
    GMTTime(1) = TimeArray(1) ' Year
    GMTTime(2) = TimeArray(2) ' Month
    GMTTime(3) = TimeArray(3) ' Day
    GMTTime(4) = TimeArray(4) + 8 ' Add 8 hours to local time
    GMTTime(5) = TimeArray(5) ' Minute
    GMTTime(6) = TimeArray(6) ' Second
    GMTTime(7) = TimeArray(7) ' Day of Year
    If GMTTime(4) >= 24 Then
      GMTTime(4) = GMTTime(4) - 24 ' Subtract 24 hours
      GMTTime(3) = GMTTime(3) + 1  ' Increment the day
      If GMTTime(3) > DaysInMonth(GMTTime(2) - 1) Then
        If GMTTime(2) = 2 AND GMTTime(1) = 2028 Then
          If GMTTime(3) > 29 Then
            GMTTime(3) = 1
            GMTTime(2) = GMTTime(2) + 1
          EndIf
          Else
            GMTTime(3) = 1
            GMTTime(2) = GMTTime(2) + 1
        EndIf
      EndIf
      If GMTTime(2) > 12 Then
        GMTTime(2) = 1
        GMTTime(1) = GMTTime(1) + 1
      EndIf
    EndIf
    'Format Date String
    dateTime=GMTTime(1)&"-"&FormatLong(GMTTime(2),"%02d")&"-"&FormatLong(GMTTime(3),"%02d")&"T"&FormatLong(GMTTime(4),"%02d")&":"&FormatLong(GMTTime(5),"%02d")&":"&FormatLong(GMTTime(6),"%02d")&"Z"
    ' Configure Get Request - Replace X's with Your Data and add weather parameters as needed
    CWOPString2="https://send.cwop.rest/?id=XXXXXX&lat=XX.749296&long=-XXX.811980&time="&dateTime&"&tempf="&Temp&"&windspeedmph=0&windgustmph=0&winddir=244&humidity="&rH&"&rainin="+Rain
    'Begin Sending 
    Header = "Content-Type:text/plain;charset=UTF-8"
    TimerCount=TimerCount+1
    ' Send Data no more often than every 5 minutes
    If TimerCount >= 300 Then
      TimerCount = 0
      SocketRef = HTTPGet(CWOPString2, Response, Header)
    EndIf
    NextScan
EndProg
